<?php

namespace app\modules\api\controllers;

use app\controllers\AppController;
use Yii;
use yii\web\ForbiddenHttpException;


class AmoController extends AppController
{
    /**
     * @throws ForbiddenHttpException
     */
    public function behaviors(): array
    {
        $this->checkAccess();
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    /**
     * @throws ForbiddenHttpException
     */
    public function checkAccess()
    {
        if (null === (Yii::$app->request->headers['XAuthToken'] ?? null)
            || Yii::$app->request->headers['XAuthToken'] !== API_AUTH_KEY) {
            throw new ForbiddenHttpException('Forbidden');
        }
    }

}